spring.application.name=agrinexus-backend
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-12e5f68b-anurag-069b.f.aivencloud.com:15247/agrinexus_db?ssl-mode=REQUIRED}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
logging.level.org.springframework.security=INFO
ai.service.url=${AI_SERVICE_URL:https://agrinexus-ai-service.onrender.com}
